### ISSUE TITLE
Getting error: Failed to get D-Bus connection: Operation not permitted

### ISSUE THREAD

**Issue by ssimsekler** [nzamani/sap-cloud-connector-docker#18]
Hi Nabi

The docker container cannot run SCC saying "Failed to get D-Bus connection: Operation not permitted". It seems some problem around unprivileged access to systemd  as per the issue reported [here](https://serverfault.com/questions/824975/failed-to-get-d-bus-connection-operation-not-permitted).

Any systemctl start/restart fails raising similar error message.

There is a similar issue raised which is fixed; however, I am still encountering the problem. BTW, I adapted the Dockerfile to use newest SAP JVM and SCC versions:

```
...
RUN wget --no-check-certificate --no-cookies --header "Cookie: eula_3_1_agreed=tools.hana.ondemand.com/developer-license-3_1.txt; path=/;" -S https://tools.hana.ondemand.com/additional/sapcc-2.12.2-linux-x64.zip && \
    wget --no-check-certificate --no-cookies --header "Cookie: eula_3_1_agreed=tools.hana.ondemand.com/developer-license-3_1.txt; path=/;" -S https://tools.hana.ondemand.com/additional/sapjvm-8.1.059-linux-x64.rpm && \
    unzip sapcc-2.12.2-linux-x64.zip && \
    rpm -i sapjvm-8.1.059-linux-x64.rpm && \
    rpm -i com.sap.scc-ui-2.12.2-3.x86_64.rpm
...
```

Kind Regards

**Comment by sammok83** [comment]
Same issue faced as well:
https://imgur.com/a/kyTCUdw

**Comment by mario-fliegner** [comment]
Same issue here as well.

**Comment by wozjac** [comment]
Hi @sammok83, @mario-fliegner 
Hi @nzamani :)

please check my fork https://github.com/wozjac/sap-cloud-connector-docker. It has _http_ configured for the connector, so after all run it using http://localhost:8443. 

I don't know the internals of SAP Cloud Connector, but the "Connector" setting seems to be related only with the endpoint for the host; if yes, then unencrypted communication is only within the host computer running Docker.

The message you are receiving "Failed to get D-Bus connection: Operation not permitted" is irrelevant here, the connector is started and the end using java <args>. The real issue is with SSL not working properly, possibly it's an issue with Windows/Docker? I haven't check this with other systems, I don't have Linux machine and my wife refuse to share her shiny Mac and pollute it with my dirty IT stuff. 

Possibly someone more advanced with networking would be able to check it. There was a reported issue with JDK (SAP note 2745641), I tried the solution from it also, did not work.

Cheers,
Jacek

**Comment by nzamani** [comment]
Thanks for reporting, and to others for helping out!
As @wozjac said the error you get can be ignored. Docker works with PID 1, systemd etc is not needed. Also, we don't want privileged mode.

Previous versions of my docker file used a java call. With cab892f465949a88c52212090c4e7835fe9f643c the dockerfile now uses ./go.sh instead which is shipped directly from SAP. No other tweak needed anymore. Plus the mentioned change uses the latest SAPCC 2.13.0
